### ISSUE TITLE
Turn transition calls out both players

### ISSUE THREAD

**Issue by NonlinearFruit** [tjunruh/Stratego#4]
When it is transitioning to Alice's turn, it will:
- say "Alice's turn. Press space to begin."
- wait for space
- then say "Bob's move. Press enter to continue."
- wait for enter

It makes the back and forth a bit confusing 😂

**Comment by tjunruh** [comment]
So, you begin your turn, and the first thing that is displayed is what the other player did in their previous turn. The other player's name is listed rather than your own, which could be confusing. Which of the two fixes would be best? Or do you have a different proposed solution?

- say "Alice's turn. Press space to begin."
- wait for space
    - either then say "Bob's **last** move. Press enter to continue."
    - or, then say "Opponent's **last** move. Press enter to continue."
- wait for enter

Also, the back and forth may be less confusing when it is being played by two different people as is intended.

**Comment by NonlinearFruit** [comment]
The way websites like Lichess or Chess.com handle the 'what did my opponent do?' is by highlighting the start and finish square of the opponent's move. Using just text, I'm not sure what would be best. Maybe color or unicode characters could achieve it?

If the opponents start/finish of there move was displayed that could eliminate the need for multiple transitions between turns

Here is an example of what Lichess does:

![image](https://github.com/tjunruh/Stratego/assets/6962125/46418bd9-3078-40c9-84b7-c9b43e16d63a)

**Comment by tjunruh** [comment]
Thanks for the advice. I have been and will continue to think about what changes I might make.

On another note, a friend of mine made a pull request that I merged, but the build did not pass. I did some things to revert it, and I think I might have messed something up with your branch. The tag on yours says repo or workflow not found. I'm still learning a lot about git commands and what they do. Let me know if there is something I need to do to fix it, or at least if it is on my end or yours that a fix needs to be made.

**Comment by NonlinearFruit** [comment]
The makefile update should probably be fine, the issue was moving the file to the root directory (when the pipeline expected it in the `Code` directory)

<details>

<summary>Here is an explanation of the workflow file</summary>

```yaml
name: Pipeline                   # Unique name for this workflow (you can have multiples)

on: [push]                       # Trigger this workflow whenever someone pushes a commit (could have other triggers)

jobs:                            # Each job is basically a collection of scripts that run in a docker container
  build:                         # A job called 'build'
    runs-on: ubuntu-latest       # Docker container name
    steps:                       # Scripts this job should run
    - uses: actions/checkout@v3  # Import & run version 3 of the 'checkout' script to clone this repo into the container
    - name: Install dependencies # Run a script (this one installs some dependencies)
      run: sudo apt-get install -y libncurses5-dev libncursesw5-dev
    - name: Compile              # Run another script (this one does the actual build)
      run: cd Code/ && make      # <-- This failed because it expects makefile in Code/
```
</details>

<details>

<summary>Here is the relevant part of the diff on that commit which broke the pipeline</summary>

Old makefile was deleted from the Code directory and added to the root directory

![image](https://github.com/tjunruh/Stratego/assets/6962125/b74ed263-730b-40ea-a1a4-73f440dd0a37)

</details>

<details>

<summary>Here is the workflow error that was happening</summary>

![image](https://github.com/tjunruh/Stratego/assets/6962125/1a382b17-f5c3-4e78-8aa9-ffed98818766)

([source](https://github.com/tjunruh/Stratego/actions/runs/5195567541/jobs/9368420835#step:4:5))
</details>

<details>

<summary>You should be able to keep @MatthewMateusz's changes if the last line of the workflow is changed to something like this</summary>

```yaml
      run: make
```
</details>
